---
title: "Untitled"
author: "Group 5"
date: "2023-05-04"
output: html_document
---

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
options(scientific = T, digits = 3)
```

```{r init, include = FALSE}
# loading in libraries
library(ezids)
library(tidyverse)
library(readr)
library(ggplot2)
library(stringr)
library(gridExtra)
library(MASS)
library(rpart)
library(caret)
library(pROC)
library(leaps)
library(ISLR)
library(ggthemes)
library(data.table)
library(ggthemr)
library(ROCR)
library(ggpubr)
library(grid)
library(DescTools)
```

```{r}
diabetes_lasso <- read.csv("diabetes_binary_5050split_health_indicators_BRFSS2015.csv")
diabetes_lasso <- diabetes_lasso %>%
    rename("diabetes"= Diabetes_binary)
diabetes_lasso <- diabetes_lasso %>%
  rename("heart_dis" = HeartDiseaseorAttack)
diabetes_lasso <- diabetes_lasso %>%
  rename("hvy_alc" = HvyAlcoholConsump)
```

```{r, comment = ""}
library(bestglm)
library(caret)
library(pROC)
library(glmnet)

set.seed(5000)
sample1 <- sample(c(TRUE, FALSE), nrow(diabete_lasso), replace = TRUE, prob=c(0.8,0.2))
data_train <- diabetes_lasso[sample1, ]
data_test <- diabetes_lasso[!sample1, ]


```

```{r, comment = ""}
library(glmnet)

#defining target and predictor variables x and y

y_train <- diabetes_train$diabetes

x_train <- data.matrix(data_train[-c(diabetes)])

# finding optimal lambda value
cv_model1 <- cv.glmnet(x, y, alpha = 1)

#find optimal lambda value that minimizes test MSE
best_lambda1 <- cv_model1$lambda.min
best_lambda1

plot(cv_model1)

# finding features for best model
best_model1 <- glmnet(x, y, alpha = 1, lambda = best_lambda1)
coef(best_model1)

new1 = matrix(c(0,1,0,1,1,1,0,1), nrow=1, ncol=8)

#use lasso regression model to predict response value
#predict(best_model, s = best_lambda, newx = new)

y_train_predict <- predict(best_model, s = best_lambda, newx = x)

#find SST and SSE
sst1 <- sum((y - mean(y_train))^2)
sse1 <- sum((y_train_predict - y_train)^2)

#find R-Squared
rsq1 <- 1 - sse1/sst1
rsq1

# confusion matrix 
cm6_train <- confusionMatrix(y_train_predict, data_train$diabetes)

```

```{r, comment = ""}
#defining target and predictor variables x and y

y_test <- diabetes_train$diabetes

x_test <- data.matrix(data_test[-c(diabetes)])

# finding optimal lambda value
cv_model2 <- cv.glmnet(x, y, alpha = 1)

#find optimal lambda value that minimizes test MSE
best_lambda2 <- cv_model2$lambda.min
best_lambda2

plot(cv_model)

# finding features for best model
best_model2 <- glmnet(x, y, alpha = 1, lambda = best_lambda2)
coef(best_model2)

new2 = matrix(c(0,1,0,1,1,1,0,1), nrow=1, ncol=8)

#use lasso regression model to predict response value
#predict(best_model, s = best_lambda, newx = new)

y_test_predict <- predict(best_model, s = best_lambda, newx = x)

#find SST and SSE
sst2 <- sum((y - mean(y_test))^2)
sse2 <- sum((y_test_predict - y_test)^2)

#find R-Squared
rsq2 <- 1 - sse2/sst2
rsq2

# confusion matrix
cm6_test <- confusionMatrix(y_test_predict, data_test$diabetes)

```